sub_processes_research_task:
  description: >
    Analyze and document ALL sub-processes involved in the specified topic with complete detail:
    1. Document each sub-process completely:
       - Full workflow documentation
       - All inputs and outputs
       - Every stakeholder and their role
       - All dependencies and relationships
    2. Maintain complete research logs
    3. Submit comprehensive documentation for QA review
    4. Address ALL QA feedback with specific responses
    5. Verify completeness of documentation
  expected_output: >
    - Complete documentation of each sub-process
    - Full stakeholder analysis
    - Detailed process relationships
    - Research logs
    - QA feedback responses
  output_format:
    type: structured_documentation
    includes:
      - full_process_documentation
      - stakeholder_matrix
      - dependency_maps
      - research_logs
      - qa_responses
  agent: sub_processes_researcher

global_regulations_research_task:
  description: >
    Research and document ALL global regulations with complete detail:
    1. Document every regulation identified
    2. Include full compliance requirements
    3. Document implementation guidelines
    4. Maintain complete research logs
    5. Address ALL QA feedback comprehensively
  expected_output: >
    - Complete regulation documentation
    - Full compliance requirements
    - Implementation guidelines
    - Research logs
    - QA feedback responses
  output_format:
    type: structured_documentation
    includes:
      - regulation_details
      - compliance_matrix
      - implementation_guides
      - research_logs
      - qa_responses
  agent: global_regulations_researcher

uae_regulations_research_task:
  description: >
    Document ALL UAE-specific regulations with complete detail:
    1. Document every local regulation
    2. Include full compliance requirements
    3. Document implementation guidelines
    4. Maintain complete research logs
    5. Address ALL QA feedback comprehensively
  expected_output: >
    - Complete UAE regulation documentation
    - Full compliance requirements
    - Implementation guidelines
    - Research logs
    - QA feedback responses
  output_format:
    type: structured_documentation
    includes:
      - regulation_details
      - compliance_matrix
      - implementation_guides
      - research_logs
      - qa_responses
  agent: uae_regulations_researcher

standards_research_task:
  description: >
    Document ALL relevant standards with complete detail:
    1. Document every applicable standard
    2. Include full requirements
    3. Document implementation guidelines
    4. Maintain complete research logs
    5. Address ALL QA feedback comprehensively
  expected_output: >
    - Complete standards documentation
    - Full requirements
    - Implementation guidelines
    - Research logs
    - QA feedback responses
  output_format:
    type: structured_documentation
    includes:
      - standards_details
      - requirements_matrix
      - implementation_guides
      - research_logs
      - qa_responses
  agent: standards_researcher

quality_assurance_task:
  description: >
    Review ALL research outputs with complete verification:
    1. Verify completeness of every section
    2. Document specific feedback for each finding
    3. Maintain detailed feedback logs
    4. Track all researcher responses
    5. Verify requirement coverage
    6. Provide final verification only when complete
  dependencies:
    - sub_processes_research_task
    - global_regulations_research_task
    - uae_regulations_research_task
    - standards_research_task
  expected_output: >
    - Complete verification logs
    - Detailed feedback
    - Requirement coverage analysis
    - Response tracking
    - Final verification status
  output_format:
    type: verification_documentation
    includes:
      - verification_logs
      - feedback_matrix
      - requirement_coverage
      - response_tracking
      - final_status
  agent: quality_assurance_expert

reporting_task:
  description: >
    Create comprehensive report including ALL research findings:
    1. Include EVERY detail from research outputs
    2. Include ALL QA feedback and responses
    3. Maintain cross-reference index
    4. Create complete appendices
    5. Verify inclusion of all inputs
  dependencies:
    - quality_assurance_task
  expected_output: >
    - Complete executive summary
    - Full research findings
    - All QA feedback and responses
    - Cross-reference index
    - Complete appendices
  output_format:
    type: comprehensive_report
    includes:
      - executive_summary
      - full_findings
      - qa_documentation
      - cross_references
      - appendices
  agent: reporting_analyst