sub_processes_research_task:
  description: >
    Research and document ALL {topic} sub-processes that are essential components to establish {topic} with complete and latest detail up to {current_date}:
    1- Search for up-to-date sub-processes of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for sub-processes and workflows
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6- Suggest PRCT (Process - Risk - Control - Tests) Matrix for each point:
      A- Process : What is the process that is detailed in this point.
      B- Risk : What the the possible risk that can be associated with that point.
      C- Risk Rating: Give this risk a rating (High / Medium / Low)
      D- Control : What is the required control to mitigate the above risk (A)
      E- Test : List down the test steps needed to ensure that control is effectively mitigating the above risk (B).
  expected_output: "Complete detailed Results with reference URL for each point including documentation of sub-processes, stakeholder analysis, process relationships, and suggested PRTC Matrix for each point"
  output_format:
    type: structured_documentation
    includes:
      - full_process_documentation
      - stakeholder_matrix
      - dependency_maps
      - PRCT Matrix
  output_file: search_results/sub_processes.md
  agent: sub_processes_researcher

  
global_regulations_research_task:
  description: >
    Research and document ALL global regulations  of {topic} with complete and  latest detail up to {current_date}:
    1- Search for up-to-date global regulations  of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for global regulations.
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6- Suggest PRCT (Process - Risk - Control - Tests) Matrix for each point:
      A- Process : What is the process that is detailed in this point.
      B- Risk : What the the possible risk that can be associated with that point.
      C- Risk Rating: Give this risk a rating (High / Medium / Low)
      D- Control : What is the required control to mitigate the above risk (A)
      E- Test : List down the test steps needed to ensure that control is effectively mitigating the above risk (B).
  expected_output: "Complete detailed Results with reference URL for each point including global regulation documentation, full compliance requirements, implementation guidelines, and suggested PRTC Matrix for each point"
  output_format:
    type: structured_documentation
    includes:
      - regulation_details
      - compliance_matrix
      - implementation_guides
      - PRCT Matrix
  output_file : search_results/global_regulations.md
  agent: global_regulations_researcher

uae_regulations_research_task:
  description: >
    Document ALL UAE-specific regulations with complete and  latest detail up to {current_date}:
    1- Search for up-to-date UAE regulations  of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for UAE regulations.
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6- Suggest PRCT (Process - Risk - Control - Tests) Matrix for each point:
      A- Process : What is the process that is detailed in this point.
      B- Risk : What the the possible risk that can be associated with that point.
      C- Risk Rating: Give this risk a rating (High / Medium / Low)
      D- Control : What is the required control to mitigate the above risk (A)
      E- Test : List down the test steps needed to ensure that control is effectively mitigating the above risk (B).
  expected_output: "Complete detailed Results with reference URL for each point including UAE regulation documentation, full compliance requirements, implementation guidelines, and suggested PRTC Matrix for each point"
  output_format:
    type: structured_documentation
    includes:
      - regulation_details
      - compliance_matrix
      - implementation_guides
      - PRCT Matrix
  output_file: search_results/uae_regulations.md
  agent: uae_regulations_researcher

standards_research_task:
  description: >
    Document ALL relevant {topic} standards with complete and  latest detail up to {current_date}:
    1- Search for up-to-date standards of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for standards.
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6- Suggest PRCT (Process - Risk - Control - Tests) Matrix for each point:
      A- Process : What is the process that is detailed in this point.
      B- Risk : What the the possible risk that can be associated with that point.
      C- Risk Rating: Give this risk a rating (High / Medium / Low)
      D- Control : What is the required control to mitigate the above risk (A)
      E- Test : List down the test steps needed to ensure that control is effectively mitigating the above risk (B).
  expected_output: "Detailed Results with reference URL for each point including standards documentation, full requirements, implementation guidelines, and suggested PRTC Matrix for each point"
  output_format:
    type: structured_documentation
    includes:
      - standards_details
      - requirements_matrix
      - implementation_guides
      - PRCT Matrix
  output_file: search_results/standards.md
  agent: standards_researcher

risk_research_task:
  description: >
    Document ALL relevant {topic} risks with complete and  latest detail up to {current_date}:
    1- Search for up-to-date risks of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for risks.
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6- Suggest PRCT (Process - Risk - Control - Tests) Matrix for each point:
      A- Process : What is the process that is detailed in this point.
      B- Risk : What the the possible risk that can be associated with that point.
      C- Risk Rating: Give this risk a rating (High / Medium / Low)
      D- Control : What is the required control to mitigate the above risk (A)
      E- Test : List down the test steps needed to ensure that control is effectively mitigating the above risk (B).
  expected_output: "Numbered list of top 10 risks with risk description, likelihood assessment, potential impact, source URLs, and suggested PRTC Matrix for each point"
  output_format:
    type: structured_documentation
    includes:
      - risk_details
      - PRCT Matrix
  output_file: search_results/risk_analysis.md
  agent: risk_researcher

prct_compilation_task:
  description: >
    Compile and organize ALL PRCT matrices from research outputs:
    1. Read all PRCT matrices from task outputs and result files
    2. Categorize processes into logical groups
    3. Within each process category:
       - Prioritize risks from highest to lowest
       - Aggregate related RCT entries while preserving all details
    4. Create comprehensive compiled PRCT matrix including:
       - Process Category
       - Process Name
       - Process Risk
       - Risk Rating
       - Control Measures
       - Test Steps
  dependencies:
    - sub_processes_research_task
    - global_regulations_research_task
    - uae_regulations_research_task
    - standards_research_task
    - risk_research_task
  expected_output: "Comprehensive PRCT matrix compilation with categorized processes, prioritized risks, complete control measures, and detailed test steps"
  output_format:
    type: structured_documentation
    includes:
      - process_categories
      - risk_prioritization
      - control_measures
      - test_procedures
  output_file: search_results/PRCT.md
  agent: prct_compilation_agent

reporting_task:
  description: >
    Compile ALL research findings from search_results folder into professional pre-audit report.
    Include verbatim content from source files and ensure all transaction IDs/user mentions are preserved.
  agent: reporting_analyst
  output_file: Pre_Audit_Report.md
  expected_output: "Comprehensive report with Executive Summary, Detailed Findings, Compiled PRCT Matrix, and Complete Source References"
  context:
    - sub_processes_research_task
    - global_regulations_research_task
    - uae_regulations_research_task
    - standards_research_task
    - risk_research_task
    - prct_compilation_task
  report_structure:
    sections:
      - title: Executive Summary
        components:
          - Audit Scope
          - Key Statistics
      - title: Process Documentation
        content_source: search_results/sub_processes.md
      - title: Global Regulations
        content_source: search_results/global_regulations.md
      - title: UAE Regulations
        content_source: search_results/uae_regulations.md
      - title: Risk Analysis
        content_source: search_results/risk_analysis.md
      - title: Compiled PRCT Matrix
        content_source: search_results/PRCT.md
      - title: References
        components:
          - All source URLs from research logs
  output_format:
    type: structured_documentation
    includes:
      - executive_summary
      - process_documentation
      - global_regulations
      - uae_regulations
      - risk_analysis
      - PRCT_matrix
      - references
  output_file: Pre_Audit_Report.md