sub_processes_research_task:
  description: >
    Research and document ALL {topic} sub-processes that are essential components to establish {topic} with complete and latest detail up to {current_date}:
    1- Search for up-to-date sub-processes of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for sub-processes and workflows
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6. Address ALL QA feedback comprehensively
  expected_output: >
    - Complete documentation of each sub-process
    - Full stakeholder analysis
    - Detailed process relationships
    - Research logs
    - QA feedback responses
  output_format:
    type: structured_documentation
    includes:
      - full_process_documentation
      - stakeholder_matrix
      - dependency_maps
      - research_logs
      - qa_responses
  agent: sub_processes_researcher

global_regulations_research_task:
  description: >
    Research and document ALL global regulations  of {topic} with complete and  latest detail up to {current_date}:
    1- Search for up-to-date global regulations  of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for global regulations.
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6. Address ALL QA feedback comprehensively
  expected_output: >
    - Complete regulation documentation
    - Full compliance requirements
    - Implementation guidelines
    - Research logs
    - QA feedback responses
  output_format:
    type: structured_documentation
    includes:
      - regulation_details
      - compliance_matrix
      - implementation_guides
      - research_logs
      - qa_responses
  agent: global_regulations_researcher

uae_regulations_research_task:
  description: >
    Document ALL UAE-specific regulations with complete and  latest detail up to {current_date}:
    1- Search for up-to-date UAE regulations  of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for UAE regulations.
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6. Address ALL QA feedback comprehensively
  expected_output: >
    - Complete UAE regulation documentation
    - Full compliance requirements
    - Implementation guidelines
    - Research logs
    - QA feedback responses
  output_format:
    type: structured_documentation
    includes:
      - regulation_details
      - compliance_matrix
      - implementation_guides
      - research_logs
      - qa_responses
  agent: uae_regulations_researcher

standards_research_task:
  description: >
    Document ALL relevant {topic} standards with complete and  latest detail up to {current_date}:
    1- Search for up-to-date standards of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for standards.
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6. Address ALL QA feedback comprehensively
  expected_output: >
    - Complete standards documentation
    - Full requirements
    - Implementation guidelines
    - Research logs
    - QA feedback responses
  output_format:
    type: structured_documentation
    includes:
      - standards_details
      - requirements_matrix
      - implementation_guides
      - research_logs
      - qa_responses
  agent: standards_researcher



risk_research_task:
  description: >
    Document ALL relevant {topic} risks with complete and  latest detail up to {current_date}:
    1- Search for up-to-date risks of {topic}
    2. Scrape content from top 5 relevant URLs
    3. Analyze scraped content for risks.
    4. Validate information against multiple sources
    5- Include the reference webpage title and URL.
    6. Address ALL QA feedback comprehensively
  expected_output: >
    Numbered list of top 10 risks with:
    - Risk description
    - Likelihood assessment
    - Potential impact
    - Source URLs
  agent: risk_researcher
  

quality_assurance_task:
  description: >
    Review ALL research outputs with complete verification:
    1. Verify completeness of every section
    2. Document specific feedback for each finding
    3. Maintain detailed feedback logs
    4. Track all researcher responses
    5. Verify requirement coverage
    6. Provide final verification only when complete
  dependencies:
    - sub_processes_research_task
    - global_regulations_research_task
    - uae_regulations_research_task
    - standards_research_task
  expected_output: >
    - Complete verification logs
    - Detailed feedback
    - Requirement coverage analysis
    - Response tracking
    - Final verification status
  output_format:
    type: verification_documentation
    includes:
      - verification_logs
      - feedback_matrix
      - requirement_coverage
      - response_tracking
      - final_status
  agent: quality_assurance_expert

reporting_task:
  description: >
    Compile ALL research findings from search_results folder into professional pre-audit report.
    Include verbatim content from source files and ensure all transaction IDs/user mentions are preserved.
  agent: reporting_analyst
  output_file: Pre_Audit_Report.md
  expected_output: >
    Comprehensive report structured with:
    1. Executive Summary
    2. Detailed Findings (all sections from search_results)
    3. Complete Source References
  context:
    - sub_processes_research_task
    - global_regulations_research_task
    - uae_regulations_research_task
    - standards_research_task
    - risk_research_task
    - quality_assurance_task
  report_structure:
    sections:
      - title: Executive Summary
        components:
          - Audit Scope
          - Key Statistics
      - title: Process Documentation
        content_source: search_results/sub_processes.md
      - title: Global Regulations
        content_source: search_results/global_regulations.md
      - title: UAE Regulations
        content_source: search_results/uae_regulations.md
      - title: Risk Analysis
        content_source: search_results/risk_analysis.md
      - title: References
        components:
          - All source URLs from research logs