sub_processes_research_task:
  description: Analyze the sub-processes involved in the specified topic, documenting each sub-process's purpose, inputs, outputs, and key stakeholders.
  expected_output:
     Detailed analysis of sub-processes.
     Share findings with QA expert for feedback.
     Incorporate QA feedback into the final report before submitting to the report writer.

  agent: sub_processes_researcher


global_regulations_research_task:
  description: Conduct research on global regulations related to the specified topic and identify key compliance requirements.
  expected_output:
     Detailed report of global regulations and compliance requirements.
     Share findings with QA expert for feedback.
     Incorporate QA feedback into the final report before submitting to the report writer.

  agent: global_regulations_researcher

uae_regulations_research_task:
  description: Conduct research on UAE-specific regulations related to the specified topic and identify key compliance requirements.
  expected_output:
     Detailed report of UAE-specific regulations and compliance requirements.
     Share findings with QA expert for feedback.
     Incorporate QA feedback into the final report before submitting to the report writer.

  agent: uae_regulations_researcher


standards_research_task:
  description: Research and analyze various standards related to the specified topic from reputable sources (globally and within the UAE).
  expected_output:
     Comprehensive list of key standards, including their titles, descriptions, requirements, and compliance dates.
     Share findings with QA expert for feedback.
     Incorporate QA feedback into the final report before submitting to the report writer.

  agent: standards_researcher

quality_assurance_task:
  description: Review and verify the research results from all researchers. Provide feedback or recommendations to improve accuracy, completeness, and alignment with requirements.
  dependencies:
     global_regulations_research_task
     uae_specific_regulations_research_task
     sub_processes_analysis_task
     standards_compliance_task

  expected_output:
     Direct feedback provided to each researcher for necessary revisions or enhancements.
  agent: quality_assurance_expert

reporting_task:
  description: Compile all verified research findings into a comprehensive final report, ensuring alignment and consistency across all sections.
  dependencies:
     global_regulations_research_task
     uae_specific_regulations_research_task
     sub_processes_analysis_task
     standards_compliance_task
     qa_review_task
  expected_output:
     Executive Summary; Overview of key findings, risks, and recommendations.
     Global Regulations Section ; Detailed analysis of global compliance requirements.
     UAE-Specific Regulations Section; Focus on regional legal and compliance frameworks.
     Sub-Processes Analysis; Breakdown of operational workflows and efficiency opportunities.
     Standards Compliance Section;  Review of applicable standards and their implementation status.
     Highlight critical areas requiring attention (e.g., compliance , high-risk processes).
      
  agent: reporting_analyst
